### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by dayne** [gina-alaska/ttnmanager#12]
since this is public there needs to be a license file associated with this - this should be approved by the DNR Tundra Travel Managers

**Comment by dayne** [comment]
This thread needs this link:
http://choosealicense.com/

If Melissa (DNR) is OK with us picking we should go with:
http://choosealicense.com/licenses/mit/

**Comment by onudson** [comment]
Melissa had no preference at this morning's meeting (2/13).  We'll proceed with MIT, send her the link, then she'll let us know if DNR prefers otherwise.
