### ISSUE TITLE
Update WMS to use ttn.gina.alaska.edu

### ISSUE THREAD

**Issue by smacfarlane** [gina-alaska/ttnmanager#42]

**Comment by dayne** [comment]
Jay,

Can you update the OGC config for Tundra Travel WMS to point at the API hosted on ttn.gina.alaska.edu instead of the ttn.herkoapp.com.

-dayne

**Comment by spruceboy** [comment]
Done.

- Jay Cable - jay@alaska.edu - (907)474-1856 -
- Geographic Information Network of Alaska -  University of Alaska  -
